(start_action tile02 yellow blue)
(--> tile03 yellow blue)
(--> tile04 yellow blue)
(--> tile05 yellow blue)
(--> tile06 yellow blue)
(--> tile07 yellow blue)
(--> tile17 yellow blue)
(--> tile12 yellow blue)
(--> tile22 yellow blue)
(--> tile27 yellow blue)
(--> tile37 yellow blue)
(--> tile32 yellow blue)
(--> tile42 yellow blue)
(--> tile47 yellow blue)
(--> tile57 yellow blue)
(--> tile56 yellow blue)
(--> tile55 yellow blue)
(--> tile54 yellow blue)
(--> tile52 yellow blue)
(--> tile53 yellow blue)
(end_action )
(start_action tile24 yellow blue)
(--> tile25 yellow blue)
(--> tile35 yellow blue)
(--> tile34 yellow blue)
(end_action )
; cost = 2 (general cost)